name: ci
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.5'

    - name: Build and publish
      run: rake publish
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PUSH_KEY: ${{ secrets.DOCKER_PUSH_KEY }}

    - name: Archive action artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
            build/artifacts/*

    # - name: Upload artifacts to release
    #   if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    #   uses: svenstaro/upload-release-action@v2
    #   with:
    #     repo_token: ${{ secrets.GITHUB_TOKEN }}
    #     tag: ${{ github.ref }}
    #     file: build/artifacts/*
    #     file_glob: true
    #     overwrite: true

    - name: Upload artifacts to release
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/artifacts/*"
        bodyFile: "build/release_notes"
        token: ${{ secrets.GITHUB_TOKEN }}
