name: publish

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.5'

    - name: env
      run: env
    - name: Check build info
      run: rake info

    - name: Build and publish
      run: rake publish
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PUSH_KEY: ${{ secrets.DOCKER_PUSH_KEY }}

    - uses: actions/upload-artifact@v2
      with:
        name: packages
        path: |
          build/artifacts/*
